# https://www.digitalocean.com/community/tutorials/how-to-install-docker-compose-on-ubuntu-16-04
# Make sure to use: /usr/bin/local/docker-compose
services:

  sphinx-util:
    build: ./utils
    image: sphinx-doc-utils:0.1.0

  sphinx-docs:
    depends_on:
      - sphinx-util
    build: ./docs
    image: sphinx-doc-docs:0.1.0
    ports:
      - 8080:80
