---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: sphinx-doc-docs
  namespace: kube-system
spec:
  ingressClassName: nginx
  rules:
  - host: sphinx-doc-docs.test
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: sphinx-doc-docs
            port: 
              number: 8080
---
# minikube image load mp-finanses-ing-processor:latest 
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sphinx-doc-docs
spec:
  selector:
    matchLabels:
      app: sphinx-doc-docs
  template:
    metadata:
      labels:
        app: sphinx-doc-docs
    spec:
      containers:
        - name: sphinx-doc-docs
          image: docker.io/library/mp-sphinx-docs:0.1.0
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: sphinx-doc-docs
  namespace: kube-system
spec:
  type: ExternalName
  externalName: sphinx-doc-docs.default.svc.cluster.local
---
apiVersion: v1
kind: Service
metadata:
  name: sphinx-doc-docs
spec:
  type: NodePort
  selector:
    app: sphinx-doc-docs
  ports:
  - name: http
    port: 8080
    targetPort: 80
